services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    image: mhallihamza/sms_api-gateway
    container_name: api-gateway
    ports:
      - '${PORT}:3000'
    networks:
      - app-network
  
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    image: mhallihamza/sms_auth
    container_name: auth
    ports:
      - '${PORT}:3001'
    networks:
      - app-network
    
  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
    image: mhallihamza/sms_users
    container_name: users
    ports:
      - '${PORT}:3002'
    networks:
      - app-network  

  customers:
    build:
      context: .
      dockerfile: ./apps/customers/Dockerfile
    image: mhallihamza/sms_customers
    container_name: customers
    ports:
      - '${PORT}:3003'
    networks:
      - app-network
    
  appointments:
    build:
      context: .
      dockerfile: ./apps/appointments/Dockerfile
    image: mhallihamza/sms_appointments
    container_name: appointments
    ports:
      - '${PORT}:3004'
    networks:
      - app-network
    
  staff:
    build:
      context: .
      dockerfile: ./apps/staff/Dockerfile
    image: mhallihamza/sms_staff
    container_name: staff
    ports:
      - '${PORT}:3005'
    networks:
      - app-network
    
  services:
    build:
      context: .
      dockerfile: ./apps/services/Dockerfile
    image: mhallihamza/sms_services
    container_name: services
    ports:
      - '${PORT}:3006'
    networks:
      - app-network
  
  treatments:
    build:
      context: .
      dockerfile: ./apps/treatments/Dockerfile
    image: mhallihamza/sms_treatments
    container_name: treatments
    ports:
      - '${PORT}:3007'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
      